### ISSUE TITLE
Logo offer for Change Detector

### ISSUE THREAD

**Issue by familqasimov** [bernaferrari/ChangeDetection#1]
Hi friend. Please me. I was a little late to answer you.
İ make a logo. If you still want a logo, I can give it to you with great pleasure

Best regard
Famil

**Comment by bernaferrari** [comment]
Sure!

**Comment by familqasimov** [comment]
Choose what you like, dear friend, or say that you want change

![changedetection](https://user-images.githubusercontent.com/36432269/40625411-64c99356-62c3-11e8-9f92-febc5116e93c.png)

Best regard
Famil

**Comment by familqasimov** [comment]
I've sent you a few small changes to your chosen logo. Please select which one you like.

![changedetection](https://user-images.githubusercontent.com/36432269/40633759-c800629e-6302-11e8-80d7-5555bc2807e0.png)

**Comment by bernaferrari** [comment]
Great job! The last blue on the right looks perfect, for me.. The outline would be nice for an iOS project, but on Android, with Adaptive Icon, it doesn't work fine.

**Comment by familqasimov** [comment]
Ok my friend. Can I sent a PR to the logo?

**Comment by bernaferrari** [comment]
Sure!
