### ISSUE TITLE
Callbacks and coroutines?

### ISSUE THREAD

**Issue by dmytrodanylyk** [bernaferrari/ChangeDetection#10]
Is there a reason why you have callbacks in your repositories and data source classes and use coroutines in your ViewModel?

I suggest making all public fun of repositories `suspended`. See [this](https://github.com/dmytrodanylyk/android-architecture/blob/todo-mvp-kotlin-coroutines/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/data/source/local/TasksLocalDataSource.kt#L43) example.

**Comment by bernaferrari** [comment]
> Is there a reason why you have callbacks in your repositories and data source classes and use coroutines in your ViewModel?

Yes! Lack of knowledge!
I have only a few weeks from experience with coroutines (and a few months with rxjava), so these things are still kind of new and sometimes hard for me. The coroutines/suspend functions inside the app were supposed to simplify the cases where callbacks became unnecessary.

However.. after realising you did the hard work converting them, I went ahead and just pushed the app for full coroutines (totally inspired by your app, I had no idea the `withContext(appExecutors.ioContext)` could replace those ugly AppExecutors).

So, consider it done!
https://github.com/bernaferrari/ChangeDetection/commit/f2742df121e3f84dedd35f2699851032aa2bc6a7

Thanks for the feedback.
If you have any other comment, suggestion or feedback, I am open!

**Comment by dmytrodanylyk** [comment]
👍

**Comment by bernaferrari** [comment]
@dmytrodanylyk I am having the following regression since the full coroutines migration:

https://www.reddit.com/r/androiddev/comments/8rylh6/weekly_questions_thread_june_18_2018/e0z20bj
