### ISSUE TITLE
Dismiss Alert on diff view

### ISSUE THREAD

**Issue by AndreaCioccarelli** [bernaferrari/ChangeDetection#15]
This is more a refinement than an issue, you should call `Alerted.dismiss()` when opening a page, to avoid having the view intrused

![](https://i.imgur.com/d03WvFJ.jpg)

**Comment by bernaferrari** [comment]
I fixed this yesterday. Great catch!
https://github.com/bernaferrari/ChangeDetection/commit/cb49fe31d893ed7e7572deeae6105879b14245c5
