### ISSUE TITLE
Black corners on CardView

### ISSUE THREAD

**Issue by AndreaCioccarelli** [bernaferrari/ChangeDetection#20]
![](https://i.imgur.com/aCVupVy.jpg)

**Comment by bernaferrari** [comment]
This is really really weird. It is perfect here. I forgot, but what device and Android version are you using??

**Comment by AndreaCioccarelli** [comment]
OnePlus 5, Android 8.1.0, OxygenOS 5.1.5

**Comment by bernaferrari** [comment]
This is super weird. While I don't have a OnePlus device, so I tested on emulator and there wasn't any issue. I'm afraid you will need to debug it yourself if you want to find the cause.

There is nothing weird on item_text_selector.xml:

```xml
<android.support.design.card.MaterialCardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/container"
    android:layout_width="112dp"
    android:layout_height="match_parent"
    android:layout_marginLeft="4dp"
    android:layout_marginRight="4dp"
    android:layout_marginTop="8dp"
    android:layout_marginBottom="8dp"
    android:clickable="true"
    android:focusable="true"
    app:cardBackgroundColor="?standardCardColor"
    app:cardCornerRadius="8dp"
    app:cardElevation="0dp">
```

**Comment by AndreaCioccarelli** [comment]
Ok I'm gonna check it out 🙃💪

**Comment by bernaferrari** [comment]
Hey, did you identify anything?

**Comment by AndreaCioccarelli** [comment]
Nothing new... :(

**Comment by AndreaCioccarelli** [comment]
I will test it on some other devices

**Comment by bernaferrari** [comment]
Lol, I got good news! After updating all dependencies and etc (Google changed A LOT OF THINGS recently), I got something that kind of resambles what you were getting. I'm refactoring everything, might take a few weeks to be ready, but I just wanted to tell you so.. Hahaha

**Comment by AndreaCioccarelli** [comment]
Android developers karma! Hahaha
