### ISSUE TITLE
set a threshold for diff

### ISSUE THREAD

**Issue by steko** [bernaferrari/ChangeDetection#24]
Hi, I discovered this app a few days ago and it looks really great. Thank you for creating it!

I found myself puzzling with a page that will be updated 10 times a year, but using the app I found out that the current date is shown in the page and will update daily.

http://statistica.comune.genova.it/pubblicazioni/periodiche.php

The actual content does not change, only a single line in the HTML source corresponding to the date.

So I thought maybe there could be a threshold setting to ignore changes below a certain diff size. What do you think?

**Comment by bernaferrari** [comment]
I really need and want to do that, but I have no ETA.

**Comment by bernaferrari** [comment]
2 years in, Compose is only getting stable now :(
