### ISSUE TITLE
Wrong diff colors for added and removed text

### ISSUE THREAD

**Issue by sm4rk0** [bernaferrari/ChangeDetection#26]
I'm running 2.1 from F-Droid and have noticed that added text is in red and removed text is in green. Couldn't find the point in code where this is swapped...

**Comment by bernaferrari** [comment]
https://github.com/bernaferrari/ChangeDetection/blob/1d67917a713b56954d0ece5d1cc823098ae790c8/app/src/main/java/com/bernaferrari/changedetection/detailstext/TextFragment.kt#L144

Here. I'm currently re-writing a great part of the app, I'll keep a look into this.
