### ISSUE TITLE
( BUG ChangeDetection Current Version 2.2 ) The application crashes when I click on the Settings button

### ISSUE THREAD

**Issue by friendsmobile** [bernaferrari/ChangeDetection#30]
# Project Information

* Repository:  https://github.com/bernaferrari/ChangeDetection
* Project Name:  ChangeDetection
* My Github Account: https://github.com/friendsmobile
* Download the application:  https://play.google.com/store/apps/details?id=com.bernaferrari.changedetection

# Expected behavior

When I click on the Settings button, all options in the Settings button should be displayed and the application should not be crashed.

# Actual behavior

 The application crashes when I click on the Settings button

#### How to reproduce

* [Download ](https://play.google.com/store/apps/details?id=com.bernaferrari.changedetection)the application
*  cancel the NEW Tracking  box
* click on the seething button 
* Note the Error

* Browser/App version: 2.2 
* Operating system: 6.0

#### Recording Of The Bug

![20190709_150453](https://user-images.githubusercontent.com/51118734/60882306-66cc3400-a1fc-11e9-87c4-3f6f4d91aece.gif)

#### Logcat

<pre><code>E/AndroidRuntime(11280): FATAL EXCEPTION: main

E/AndroidRuntime(11280): Process: com.bernaferrari.changedetection, PID: 11280

E/AndroidRuntime(11280): android.view.InflateException: Binary XML file line #35: Error inflating class androidx.appcompat.widget.SwitchCompat

E/AndroidRuntime(11280): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)

E/AndroidRuntime(11280): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)

E/AndroidRuntime(11280): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)

E/AndroidRuntime(11280): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)

E/AndroidRuntime(11280): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)

E/AndroidRuntime(11280): 	at b.k.a.e.b()

E/AndroidRuntime(11280): 	at b.k.a.e.b()

E/AndroidRuntime(11280): 	at androidx.recyclerview.widget.RecyclerView$a.a()

E/AndroidRuntime(11280): 	at androidx.recyclerview.widget.RecyclerView$p.a()

E/AndroidRuntime(11280): 	at androidx.recyclerview.widget.RecyclerView$p.b()

E/AndroidRuntime(11280): 	at androidx.recyclerview.widget.RecyclerView$p.d()

E/AndroidRuntime(11280): 	at androidx.recyclerview.widget.LinearLayoutManager$c.a()

E/AndroidRuntime(11280): 	at androidx.recyclerview.widget.LinearLayoutManager.a()

E/AndroidRuntime(11280): 	at androidx.recyclerview.widget.LinearLayoutManager.a()

E/AndroidRuntime(11280): 	at androidx.recyclerview.widget.LinearLayoutManager.e()

E/AndroidRuntime(11280): 	at androidx.recyclerview.widget.RecyclerView.B()

E/AndroidRuntime(11280): 	at androidx.recyclerview.widget.RecyclerView.onMeasure()

E/AndroidRuntime(11280): 	at android.view.View.measure(View.java:17951)

E/AndroidRuntime(11280): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5797)

E/AndroidRuntime(11280): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)

E/AndroidRuntime(11280): 	at android.view.View.measure(View.java:17951)

E/AndroidRuntime(11280): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5797)

E/AndroidRuntime(11280): 	at androidx.coordinatorlayout.widget.CoordinatorLayout.a()

E/AndroidRuntime(11280): 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure()

E/AndroidRuntime(11280): 	at android.view.View.measure(View.java:17951)

E/AndroidRuntime(11280): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5797)

E/AndroidRuntime(11280): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)

E/AndroidRuntime(11280): 	at android.view.View.measure(View.java:17951)

E/AndroidRuntime(11280): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5797)

E/AndroidRuntime(11280): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)

E/AndroidRuntime(11280): 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure()

E/AndroidRuntime(11280): 	at android.view.View.measure(View.java:17951)

E/AndroidRuntime(11280): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5797)

E/AndroidRuntime(11280): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)

E/AndroidRuntime(11280): 	at android.view.View.measure(View.java:17951)

E/AndroidRuntime(11280): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5797)

E/AndroidRuntime(11280): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)

E/AndroidRuntime(11280): 	at android.view.View.measure(View.java:17951)

E/AndroidRuntime(11280): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5797)

E/AndroidRuntime(11280): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)

E/AndroidRuntime(11280): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)

E/AndroidRuntime(11280): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)

E/AndroidRuntime(11280): 	at android.view.View.measure(View.java:17951)

E/AndroidRuntime(11280): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5797)

E/AndroidRuntime(11280): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)

E/AndroidRuntime(11280): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2910)

E/AndroidRuntime(11280): 	at android.view.View.measure(View.java:17951)

E/AndroidRuntime(11280): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2048)

E/AndroidRuntime(11280): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1185)

E/AndroidRuntime(11280): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1406)

E/AndroidRuntime(11280): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1073)

E/AndroidRuntime(11280): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5988)

E/AndroidRuntime(11280): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)

E/AndroidRuntime(11280): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)

E/AndroidRuntime(11280): 	at android.view.Choreographer.doFrame(Choreographer.java:550)

E/AndroidRuntime(11280): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)

E/AndroidRuntime(11280): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(11280): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(11280): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(11280): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(11280): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(11280): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(11280): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(11280): 	at com.android.interna
</code></pre>

**Comment by bernaferrari** [comment]
Solved on last version (still in testing).
