### ISSUE TITLE
( BUG ChangeDetection Current Version 2.2 ) The application crashes when I click on the refresh icon or click on  the  last sync

### ISSUE THREAD

**Issue by friendsmobile** [bernaferrari/ChangeDetection#31]
# Project Information

* Repository:  https://github.com/bernaferrari/ChangeDetection
* Project Name:  ChangeDetection
* My Github Account: https://github.com/friendsmobile
* Download the application:  https://play.google.com/store/apps/details?id=com.bernaferrari.changedetection

# Expected behavior

The update should be refresh when I click the refresh icon And when I click on the last sync, the application should not crash

# Actual behavior

The application crashes when I click on the refresh icon or click on  the  last sync

#### How to reproduce

* [Download ](https://play.google.com/store/apps/details?id=com.bernaferrari.changedetection)the application
*  create the New Tracking  ( type the title facebook and type the URL www.facebook.com)
* After creating new tracking, click Refresh Icon
* Note the Error

* Browser/App version: 2.2 
* Operating system: 6.0

#### Recording Of The Bug

![20190709_155553](https://user-images.githubusercontent.com/51118734/60883002-e9a1be80-a1fd-11e9-8ad1-caec449666b2.gif)

#### Logcat

<pre><code>E/AndroidRuntime(11946): FATAL EXCEPTION: main

E/AndroidRuntime(11946): Process: com.bernaferrari.changedetection, PID: 11946

E/AndroidRuntime(11946): android.view.InflateException: Binary XML file line #36: Error inflating class androidx.appcompat.widget.AppCompatImageView

E/AndroidRuntime(11946): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)

E/AndroidRuntime(11946): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)

E/AndroidRuntime(11946): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)

E/AndroidRuntime(11946): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)

E/AndroidRuntime(11946): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)

E/AndroidRuntime(11946): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)

E/AndroidRuntime(11946): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)

E/AndroidRuntime(11946): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)

E/AndroidRuntime(11946): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)

E/AndroidRuntime(11946): 	at android.view.View.inflate(View.java:18945)

E/AndroidRuntime(11946): 	at b.j.a.a.<init>()

E/AndroidRuntime(11946): 	at b.j.a.a.<init>()

E/AndroidRuntime(11946): 	at b.j.a.f$a.b()

E/AndroidRuntime(11946): 	at com.bernaferrari.changedetection.Y.a()

E/AndroidRuntime(11946): 	at com.bernaferrari.changedetection.Y.a()

E/AndroidRuntime(11946): 	at androidx.lifecycle.LiveData.b()

E/AndroidRuntime(11946): 	at androidx.lifecycle.LiveData.a()

E/AndroidRuntime(11946): 	at androidx.lifecycle.LiveData.b()

E/AndroidRuntime(11946): 	at androidx.lifecycle.x.b()

E/AndroidRuntime(11946): 	at com.bernaferrari.changedetection.da.invokeSuspend()

E/AndroidRuntime(11946): 	at f.c.b.a.a.resumeWith()

E/AndroidRuntime(11946): 	at kotlinx.coroutines.DispatchedTask.run()

E/AndroidRuntime(11946): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(11946): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(11946): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(11946): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(11946): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(11946): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(11946): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(11946): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime(11946): Caused by: java.lang.reflect.InvocationTargetException

E/AndroidRuntime(11946): 	at java.lang.reflect.Constructor.newInstance(Native Method)

E/AndroidRuntime(11946): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)

E/AndroidRuntime(11946): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)

E/AndroidRuntime(11946): 	... 29 more

E/AndroidRuntime(11946): Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f070068

E/AndroidRuntime(11946): 	at android.content.res.Resources.getResourceName(Resources.java:2413)

E/AndroidRuntime(11946): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2908)

E/AndroidRuntime(11946): 	at android.content.res.Resources.loadDrawable(Resources.java:2821)

E/AndroidRuntime(11946): 	at android.content.res.Resources.loadDrawable(Resources.java:2670)

E/AndroidRuntime(11946): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:761)

E/AndroidRuntime(11946): 	at android.widget.ImageView.<init>(ImageView.java:146)

E/AndroidRuntime(11946): 	at android.widget.ImageView.<init>(ImageView.java:135)

E/AndroidRuntime(11946): 	at androidx.appcompat.widget.AppCompatImageView.<init>()

E/AndroidRuntime(11946): 	at androidx.appcompat.widget.AppCompatImageView.<init>()

E/AndroidRuntime(11946): 	... 32 more
</code></pre>

**Comment by bernaferrari** [comment]
Hmm, just tested here and no issues. What device are you using? I've never gotten a report like that.

**Comment by friendsmobile** [comment]
I am using Samsung galaxy j7

**Comment by bernaferrari** [comment]
Should be fixed in latest version (still testing)
