### ISSUE TITLE
Need bottom menu idea

### ISSUE THREAD

**Issue by ManojBehera** [bernaferrari/ChangeDetection#35]
Hi,

Can you tell me how you have implemented bottom setting menu dialog. Have you added any third party library/ dependency ??

Click on setting icon on tool bar and it is showing Sync optioning a dialog.

**Comment by bernaferrari** [comment]
It is a simple BottomSheetDialogFragment: https://developer.android.com/reference/android/support/design/widget/BottomSheetDialogFragment
