### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [bernaferrari/ChangeDetection#9]
Hi,

Since this app is Apache v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you (we are busy at F-Droid, it can take a lot of time...)?

**Comment by bernaferrari** [comment]
Sure. I'll wait a few days until it stabilize and when I publish to play store I'll put on fdroid. If I have any questions I'll tell you. Thanks!!

**Comment by Poussinou** [comment]
No problem, do not hesitate to ask me ;)

**Comment by IzzySoft** [comment]
@bernaferrari is your waiting over? We're looking forward to process @Poussinou's request :wink:

**Comment by bernaferrari** [comment]
I actually kind of forgot about it plus didn't understand how to add it to fdroid, sorry. Go on, feel free!

**Comment by IzzySoft** [comment]
Thanks, @bernaferrari! @Poussinou already opened the request for packaging, and the bot confirmed it found no "EvilKanivel" stuff in your repo – so we should be fine to go. To make (detecting) updates easier, could you please [tag your releases](https://github.com/bernaferrari/ChangeDetection/releases)?

Less urgent, but nice to have: if you've got an idea of how to work with Fastlane or Triple-T, you could provide screenshots (and descriptions) directly from your repository here (if you have no idea, tell me and I check for F-Droid's "quick info" on this). For now I've created a template with a basic description; if you decided to maintain the description via Fastlane/Triple-T just let us know and we fix it up.

**Comment by IzzySoft** [comment]
Just as a heads-up: Your app is ready to go [as soon as you add tags](https://gitlab.com/fdroid/fdroiddata/merge_requests/3740) – all else is prepared, just the lack of tags is holding it (for a week) now. So, @bernaferrari, may I kindly ask you to provide them? Thanks in advance!

**Comment by bernaferrari** [comment]
Consider it done! https://github.com/bernaferrari/ChangeDetection/releases/tag/2.1

**Comment by IzzySoft** [comment]
Thanks a lot! I just pinged the "integrator" to proceed the merge. Shouldn't take more than a week for your app to show up on F-Droid now (provided there are no "accidents" like a delayed index update).
